INSERT INTO graphql.post (author_id, title, description, content, `date`)
VALUES (1, 'Expedita commodi non dolores sit.',
        'Veritatis occaecati harum odio similique dolores et et. Veritatis distinctio sequi quo voluptatem saepe dolor architecto. Expedita autem nobis quam maxime.',
        'Est nisi accusamus ut et. Ea molestias quaerat totam a cupiditate nostrum sint. Fuga qui maxime nisi maxime eius eaque dolores et.',
        '2014-02-03'),
       (2, 'Enim nam est corporis dolore officiis ea tempore.',
        'Sed temporibus nam quia assumenda. Omnis cupiditate sed pariatur quidem. Asperiores est itaque quae explicabo laboriosam at aliquam.',
        'Reiciendis assumenda perferendis perspiciatis laborum explicabo. Recusandae aut voluptate porro distinctio repudiandae soluta nihil. Rem qui perspiciatis corrupti voluptas quia ut delectus.',
        '2009-09-17'),
       (3, 'Quas illo fuga velit.',
        'Est beatae reprehenderit velit delectus rem quaerat ea quam. Voluptas qui mollitia ipsam animi tempora. Sed molestias non inventore placeat necessitatibus suscipit blanditiis eveniet. Molestiae exercitationem enim minus ducimus incidunt quia.',
        'Voluptatem voluptatem ut ut. Temporibus enim deleniti facilis animi expedita blanditiis. Eos perferendis exercitationem enim.',
        '1974-01-29'),
       (4, 'Nisi accusantium eos temporibus nam.',
        'Reprehenderit reiciendis dolore fugiat consectetur et eos quo ea. Eum sint omnis rerum rerum consequatur. Nihil vel eum repellat. Exercitationem molestiae tenetur quam doloribus optio velit.',
        'Ea asperiores voluptatem rerum ut. Doloribus at doloremque consequatur ad eaque quis. Ullam nulla commodi ipsum et ut. Repudiandae ut quia eum culpa sit eos.',
        '2020-06-20'),
       (5, 'Harum accusantium nesciunt qui nihil.',
        'Perspiciatis odio quia alias omnis ipsam distinctio aliquid voluptas. Et dolorem qui aliquid quisquam laborum ratione quasi minus.',
        'Eum et rerum magnam aliquam rem. Est sequi nobis minus iusto optio est deserunt. Hic consequuntur voluptas quaerat. Qui id nihil quo exercitationem.',
        '1992-06-03'),
       (6, 'Consectetur asperiores sint perferendis.',
        'Itaque qui quod sit voluptatum quam quos at dolorum. A eligendi labore assumenda repudiandae dolores numquam similique consequatur. Aut magnam voluptatem quod animi omnis.',
        'Iure officiis est eos et in. Atque laboriosam maxime est quia ipsam. Et occaecati in ipsum dolor est nesciunt. Quia tempora et officia sed aperiam non laudantium.',
        '1980-03-02'),
       (7, 'Harum vitae ab accusamus ullam doloremque praesentium eos accusantium.',
        'Sunt cum labore non nostrum nam a itaque. Eligendi laudantium aliquam sunt et fugit. Dolores ut ut exercitationem qui molestias.',
        'Est doloremque ut rerum cupiditate. Totam dolorem corrupti ea et. Asperiores molestiae quia quia quidem pariatur occaecati.',
        '2013-02-27'),
       (8, 'Eos illo quia et et.',
        'Maxime ut perferendis officiis. Velit explicabo distinctio voluptatum rerum hic neque dicta. Voluptas quasi deleniti qui et mollitia numquam molestias aliquid. Numquam omnis aut dolores.',
        'Dolorem a nesciunt et qui sed. Cumque eveniet quisquam in. Tenetur magni debitis culpa nihil perspiciatis consequatur. Illo illo quo hic consequatur dolorem at.',
        '1996-11-05'),
       (9, 'Adipisci sequi dicta delectus dolores consectetur fugiat natus.',
        'Omnis eum nesciunt qui non et beatae. Laboriosam beatae omnis aperiam hic. At debitis maxime eum sint.',
        'Voluptate incidunt qui porro vero. Aut magnam natus sit sed saepe ipsum aliquam corporis. Est dolorem architecto itaque dolorem non perferendis nulla. Quasi eos provident vel sint.',
        '1981-06-22'),
       (10, 'Doloremque sit quasi libero adipisci.',
        'Quos autem non quas provident quis. Et aut omnis aut autem ratione. Facere cum voluptate fugiat id est fuga.',
        'Fugiat accusantium vero vel exercitationem quod error. Magni ut est sunt. Saepe earum illo velit laboriosam consequatur ipsum fuga facere. Fuga cupiditate blanditiis laudantium accusamus quas nihil.',
        '2007-09-01');

INSERT INTO graphql.author (first_name, last_name, email, birthdate, added)
VALUES ('Dylan', 'VonRueden', 'crystel.lindgren@example.com', '2008-05-01', '2020-03-02 20:25:15'),
       ('Sophie', 'Mayert', 'virgie.leffler@example.com', '1991-11-20', '2010-05-08 17:22:15'),
       ('Diego', 'Dietrich', 'orin43@example.net', '2019-05-25', '2002-06-03 01:07:36'),
       ('Florencio', 'Grant', 'burley39@example.net', '2011-10-15', '2001-08-06 19:36:39'),
       ('Citlalli', 'Labadie', 'kilback.kevon@example.com', '1987-07-06', '2017-08-30 23:50:39'),
       ('Erik', 'Tremblay', 'rempel.francisco@example.com', '1989-05-03', '1976-05-22 11:59:43'),
       ('Mathilde', 'Heidenreich', 'eo''conner@example.net', '2005-11-06', '1989-03-13 13:49:13'),
       ('Carlee', 'Aufderhar', 'aida.rippin@example.org', '1980-10-27', '1983-08-26 02:42:05'),
       ('Ashlynn', 'Rohan', 'gwuckert@example.com', '1990-09-12', '1985-05-28 22:59:46'),
       ('Orlando', 'Littel', 'zgrady@example.org', '1991-07-03', '2009-06-13 02:45:27');