### GET request with a header
GET http://localhost:8080/authors/1
Accept: application/json

### GET request with a header
GET http://localhost:8080/posts/1
Accept: application/json

### Send POST request with json body
POST http://localhost:8080/graphql/query
Content-Type: application/json

{
  author(id: 1) {
    firstName
    lastName
  }
}

### Send POST request with json body
POST http://localhost:8080/graphql/query
Content-Type: application/json

{
  allAuthors {
    id
    firstName
    lastName
    birthdate
  }
}

### Send POST request with json body
POST http://localhost:8080/graphql/query
Content-Type: application/json

{
  post(id: 1) {
    id
    title
    content,
    authorId,
    author {
      firstName
      lastName
      birthdate
    }
  }
}


### Send POST request with json body
POST http://localhost:8080/graphql/query
Content-Type: application/json

{
  allPosts {
   id
   title
   content
   author {
    firstName
    lastName
   }
 }
}